### ISSUE TITLE
Hitman table isn't creating up on Database

### ISSUE THREAD

**Issue by rerdoze** [Freenex1911/FeexHitman#3]
Hello, I had a little problem with the plugin, I realized that it is not creating the Hitman table in my database, other puglins like ZaupShop and Uconomy have created the table without any problem. Can you give me any tips on how I can solve this? Or how many columns and type of variable do I need to create the table.

Thanks in advance.

**Comment by Freenex1911** [comment]
It should work, please check the logs. https://github.com/Freenex1911/FeexHitman/blob/master/FeexHitmanDatabase.cs#L203
